//autogenerated:yes
//nolint:revive,lll
package xbot_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/geometry_msgs"
)

type MapArea struct {
	msg.Package         `ros:"xbot_msgs"`
	Name                string
	Active              bool
	Angle               float64
	OutlineCount        int32
	OutlineOverlapCount int32
	OutlineOffset       float64
	Area                geometry_msgs.Polygon
	Obstacles           []geometry_msgs.Polygon
}
